name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  build:
    name: Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push the docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: nabardio/match-runner
          tag_with_ref: true
          tags: latest
